name: 更新直播源

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 (北京时间 08:00)
  workflow_dispatch:

permissions:
  contents: write  # 允许推送文件

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install requests

      - name: 运行生成脚本
        run: python update_live.py

      - name: 查看文件生成结果
        run: |
          echo "📁 当前目录文件："
          ls -la
          echo ""
          echo "📜 cmlive.txt 内容预览："
          head -n 20 cmlive.txt || echo "⚠️ 文件未生成"

      - name: 提交并推送 cmlive.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add cmlive.txt
          git diff --cached --quiet || git commit -m "📺 自动更新 cmlive.txt $(date '+%Y-%m-%d %H:%M:%S')"
          git push
